<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\HasMany;

class UserAccount extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'user_account';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'email',
        'password_hash',
        'role',
        'status',
        'last_login_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password_hash',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'last_login_at' => 'datetime',
        ];
    }

    /**
     * Override password column name for Laravel authentication.
     *
     * @return string
     */
    public function getAuthPasswordName(): string
    {
        return 'password_hash';
    }

    /**
     * Get associated Faculty profile if account belongs to a faculty member.
     */
    public function faculty(): HasOne
    {
        return $this->hasOne(Faculty::class, 'user_account_id', 'id');
    }

    /**
     * Get associated Student profile if account belongs to a student.
     */
    public function student(): HasOne
    {
        return $this->hasOne(Student::class, 'user_account_id', 'id');
    }

    /**
     * Get all feedback forms created by this user account.
     */
    public function createdFeedbackForms(): HasMany
    {
        return $this->hasMany(FeedbackForm::class, 'created_by_user_account_id', 'id');
    }

    /**
     * Get all feedback responses excluded/moderated by this user account.
     */
    public function excludedFeedbackResponses(): HasMany
    {
        return $this->hasMany(FeedbackResponse::class, 'excluded_by_user_account_id', 'id');
    }

    /**
     * Get all reports generated by this user account.
     */
    public function generatedReports(): HasMany
    {
        return $this->hasMany(Report::class, 'generated_by_user_account_id', 'id');
    }

    /**
     * Get all data import logs uploaded by this user account.
     */
    public function uploadedDataImports(): HasMany
    {
        return $this->hasMany(DataImportLog::class, 'uploaded_by_user_account_id', 'id');
    }

    /**
     * Get all system settings updated by this user account.
     */
    public function updatedSystemSettings(): HasMany
    {
        return $this->hasMany(SystemSettings::class, 'updated_by_user_account_id', 'id');
    }
}
